server:
  port: 9000

jwt-config:
  secretKeyPath: classpath:keys/jwt.key
  publicKeyPath: classpath:keys/jwt.pub
  issuer: JWT_BUILDER

spring:
  security:
    user:
      name: user
      password: password
    
  profiles:
    active: production

  datasource:
    url: jdbc:postgresql://${DB_HOST:user-api-psql}:${DB_PORT:5432}/${DB_NAME:dev}?createDatabaseIfNotExist=true
    username: ${DB_USER:psql}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10  # オプション: プールの最大サイズ
      minimum-idle: 5  # オプション: 最小アイドル接続数
      idle-timeout: 600000  # オプション: アイドルタイムアウト (ミリ秒)
      connection-timeout: 30000  # オプション: 接続タイムアウト (ミリ秒)
      pool-name: HikariPool-1  # オプション: プールの名前
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      # ddl-auto: create-drop #test-env
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          create-namespaces: true 
      repositories:
        enabled: true
